#!/usr/bin/env bash

set -e

PARENT_DIR=${1}
LAMBDA_SRC_DIR="${PARENT_DIR}/src/application"
LAMBDA_PACKAGE_DIR="${PARENT_DIR}/src/package"

#Package
(
    cd "${LAMBDA_SRC_DIR}";
    zip -X "${LAMBDA_PACKAGE_DIR}/function.zip" *;
)
